dist: focal
sudo: required
services:
  - docker

before_install:
  - docker build -t jeffreyccd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jeffreyccd/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-724285037189"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"